# Generated by Django 5.1.1 on 2025-07-10 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'ordering': ['-priority', '-date_submitted']},
        ),
        migrations.AddField(
            model_name='feedback',
            name='priority',
            field=models.CharField(choices=[('Low', 'Baixa'), ('Medium', 'Média'), ('High', 'Alta')], default='Medium', max_length=10),
        ),
    ]
