# Generated by Django 5.1.1 on 2025-07-10 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_alter_feedback_options_feedback_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pendente'), ('Resolved', 'Resolvido')], default='Pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='type',
            field=models.CharField(choices=[('Suggestion', 'Sugestão'), ('Technical', 'Suporte Técnico')], max_length=20),
        ),
    ]
