# Generated by Django 5.1.1 on 2025-07-10 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_alter_feedback_status_alter_feedback_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'ordering': ['-priority', '-date_submitted'], 'verbose_name': 'Feedback', 'verbose_name_plural': 'Feedbacks'},
        ),
        migrations.AddField(
            model_name='feedback',
            name='assigned_to',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Responsável'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='category',
            field=models.CharField(choices=[('Administrative', 'Administrativo'), ('Academic', 'Acadêmico'), ('Technical', 'Técnico'), ('Facility', 'Infraestrutura'), ('Other', 'Outro')], default='Other', max_length=20, verbose_name='Categoria'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='course',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Curso'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='date_resolved',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Resolução'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='follow_up_needed',
            field=models.BooleanField(default=False, verbose_name='Necessita Acompanhamento'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='satisfaction_rating',
            field=models.IntegerField(blank=True, null=True, verbose_name='Avaliação de Satisfação'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='semester',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Semestre'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='student_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Matrícula'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='subject',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Disciplina'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='teacher',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Professor'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='admin_note',
            field=models.TextField(blank=True, null=True, verbose_name='Nota do Administrador'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='date_submitted',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de Envio'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='message',
            field=models.TextField(verbose_name='Mensagem'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='priority',
            field=models.CharField(choices=[('Low', 'Baixa'), ('Medium', 'Média'), ('High', 'Alta'), ('Urgent', 'Urgente')], default='Medium', max_length=10, verbose_name='Prioridade'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pendente'), ('In_Progress', 'Em Andamento'), ('Resolved', 'Resolvido'), ('Closed', 'Fechado')], default='Pending', max_length=15, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='type',
            field=models.CharField(choices=[('Suggestion', 'Sugestão'), ('Technical', 'Suporte Técnico'), ('Complaint', 'Reclamação'), ('Praise', 'Elogio'), ('Doubt', 'Dúvida')], max_length=20, verbose_name='Tipo'),
        ),
    ]
