# Generated by Django 5.1.1 on 2025-07-10 04:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0004_alter_feedback_options_feedback_assigned_to_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome da Instituição')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Código Único')),
                ('domain', models.CharField(blank=True, max_length=100, verbose_name='Domínio')),
                ('address', models.TextField(blank=True, verbose_name='Endereço')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email de Contato')),
                ('logo', models.ImageField(blank=True, upload_to='institutions/logos/', verbose_name='Logo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
            ],
            options={
                'verbose_name': 'Instituição',
                'verbose_name_plural': 'Instituições',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='feedback',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='feedback.institution', verbose_name='Instituição'),
        ),
    ]
