# Generated by Django 5.1.1 on 2025-07-10 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0005_institution_feedback_institution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Endereço'),
        ),
    ]
