# Generated by Django 5.2.4 on 2025-07-21 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0008_institution_authorized_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='cnpj',
            field=models.CharField(default='00.000.000/0000-00', max_length=18, verbose_name='CNPJ'),
        ),
    ]
