# Generated by Django 5.2.4 on 2025-07-21 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0009_institution_cnpj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='cnpj',
            field=models.CharField(max_length=18, verbose_name='CNPJ'),
        ),
    ]
